services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./server_out:/app/server_out
      - ./server_out_fedbn:/app/server_out_fedbn
      - ./runs:/app/runs
      - ./eval_results_transformer.json:/app/eval_results_transformer.json
      - ./eval_results_grud.json:/app/eval_results_grud.json
      - ./eval_results_federated.json:/app/eval_results_federated.json
      - ./eval_results_ensemble.json:/app/eval_results_ensemble.json
      - ./eval_results_fedbn.json:/app/eval_results_fedbn.json
      - ./eval_results_noniid.json:/app/eval_results_noniid.json
      - ./eval_results_transformer_fl.json:/app/eval_results_transformer_fl.json
    environment:
      - SEPSIS_MODEL_PATH=/app/server_out/global_best.pt
      - SEPSIS_MODEL_TYPE=grud
      - SEPSIS_SCALER_PATH=/app/data/processed/patients/scaler.json

  api:
    build: .
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./server_out:/app/server_out
    environment:
      - SEPSIS_MODEL_PATH=/app/server_out/global_best.pt
      - SEPSIS_MODEL_TYPE=grud
      - SEPSIS_SCALER_PATH=/app/data/processed/patients/scaler.json
